export const mockupBerichte = [
	{
		id: "3f0a0c5a-d5d4-4d0b-b2d1-e2e9e1e0e0e0",
		siteLang: "de",
		siteTitle: "Bericht 1",
		siteDescription: "Dies ist eine Beschreibung für Bericht 1.",
		siteColor: "abendstimmung",
		headerMenu: true,
		siteSearch: true,
		skipFirstChapter: false,
		stageTitle: "Einleitung",
		stageDescription: "Kurze Einführung in Bericht 1",
		sitePath: "/spezial/bericht_1",
		coverImageOption: "upload", // or "default"
		coverImageAltText: "Ein Bild von Bericht 1",
		coverImageUpload: "cover-image-1.jpg",
		domainURL: "https://wien.gv.at",
		directoryPath: "/spezial/bericht_1",
		copyrightText: "Stadt Wien – Kommunikation und Medien",
		navigationElements: {
			search: true,
			dropdown: true,
			languageSelection: true,
		},
		languages: [
			{ text: "Deutsch", link: "https://wien.gv.at/spezial/bericht_1" },
			{
				text: "Türkçe",
				link: "https://wien.gv.at/spezial/bericht_1_tr",
			},
			{
				text: "English",
				link: "https://wien.gv.at/spezial/bericht_1_en",
			},
		],
		chapterColors: [
			{ chapterNumber: 1, color: "morgenrot" },
			{ chapterNumber: 2, color: "flieder" },
		],
		footer: {
			title: "Fragen zum Berichte-Framework?",
			department: "MA 53",
			division: "Digitales Content Management und Produktentwicklung",
			emailText: "Kontakt",
			email: "mailto:redaktion@wien.gv.at",
			phoneText: "Rufen Sie uns an",
			phone: "tel:431400081049",
			imprintText: "Impressum",
			imprintURL: "https://www.wien.gv.at/info/impressum.html",
			privacyText: "Datenschutz",
			privacyURL: "https://www.wien.gv.at/info/datenschutz/index.html",
			accessibilityText: "Barrierefreiheit",
			accessibilityURL: "https://www.wien.gv.at/info/barrierefreiheit.html",
		},
	},
	{
		id: "3f0a0c5a-d5d4-4d0b-b2d1-e2e9e1e0e0e1",
		siteLang: "en",
		siteTitle: "Report 2",
		siteDescription: "This is a description for Report 2.",
		siteColor: "goldgelb",
		headerMenu: false,
		siteSearch: true,
		skipFirstChapter: true,
		stageTitle: "Overview",
		stageDescription: "A brief overview of Report 2",
		sitePath: "/special/report_2",
		coverImageOption: "default", // or "upload"
		coverImageAltText: "Default cover image for Report 2",
		coverImageUpload: null, // No uploaded image
		domainURL: "https://vienna.gv.at",
		directoryPath: "/special/report_2",
		copyrightText: "City of Vienna – Communication and Media",
		navigationElements: {
			search: true,
			dropdown: false,
			languageSelection: true,
		},
		languages: [
			{
				text: "English",
				link: "https://vienna.gv.at/special/report_2",
			},
			{
				text: "Español",
				link: "https://vienna.gv.at/special/report_2_es",
			},
		],
		chapterColors: [
			{ chapterNumber: 1, color: "wasserblau" },
			{ chapterNumber: 2, color: "morgenrot" },
		],
		footer: {
			title: "Questions about the Reports Framework?",
			department: "MA 53",
			division: "Digital Content Management and Product Development",
			emailText: "Contact Us",
			email: "mailto:editor@vienna.gv.at",
			phoneText: "Call us",
			phone: "tel:431400081050",
			imprintText: "Imprint",
			imprintURL: "https://www.vienna.gv.at/info/imprint.html",
			privacyText: "Privacy Policy",
			privacyURL: "https://www.vienna.gv.at/info/privacy.html",
			accessibilityText: "Accessibility",
			accessibilityURL: "https://www.vienna.gv.at/info/accessibility.html",
		},
	},
	{
		id: "3f0a0c5a-d5d4-4d0b-b2d1-e2e9e1e0e0e2",
		siteLang: "de",
		siteTitle: "Bericht 3",
		siteDescription: "Dies ist eine Beschreibung für Bericht 3.",
		siteColor: "nebelgrau",
		headerMenu: true,
		siteSearch: false,
		skipFirstChapter: false,
		stageTitle: "Hauptteil",
		stageDescription: "Hauptinhalt von Bericht 3",
		sitePath: "/spezial/bericht_3",
		coverImageOption: "upload", // or "default"
		coverImageAltText: "Ein Bild von Bericht 3",
		coverImageUpload: "cover-image-3.jpg",
		domainURL: "https://wien.gv.at",
		directoryPath: "/spezial/bericht_3",
		copyrightText: "Stadt Wien – Kommunikation und Medien",
		navigationElements: {
			search: false,
			dropdown: true,
			languageSelection: false,
		},
		languages: [
			{ text: "Deutsch", link: "https://wien.gv.at/spezial/bericht_3" },
		],
		chapterColors: [
			{ chapterNumber: 1, color: "frischgruen" },
			{ chapterNumber: 2, color: "flieder" },
			{ chapterNumber: 3, color: "morgenrot" },
		],
		footer: {
			title: "Fragen zum Berichte-Framework?",
			department: "MA 53",
			division: "Digitales Content Management und Produktentwicklung",
			emailText: "Kontakt",
			email: "mailto:redaktion@wien.gv.at",
			phoneText: "Rufen Sie uns an",
			phone: "tel:431400081049",
			imprintText: "Impressum",
			imprintURL: "https://www.wien.gv.at/info/impressum.html",
			privacyText: "Datenschutz",
			privacyURL: "https://www.wien.gv.at/info/datenschutz/index.html",
			accessibilityText: "Barrierefreiheit",
			accessibilityURL: "https://www.wien.gv.at/info/barrierefreiheit.html",
		},
	},
]
